Init commit for HA neutron-l3-agent
- added crm_neutron task to playbook
- udpated neutron-l3-agent.conf upstart file to support pid file
- massive refactoring to neutron-agent-l3 OCF resource

diff --git a/playbooks/openstack-ha/templates/resource_agents/neutron-agent-l3 b/playbooks/openstack-ha/templates/resource_agents/neutron-agent-l3
--- a/playbooks/openstack-ha/templates/resource_agents/neutron-agent-l3
+++ b/playbooks/openstack-ha/templates/resource_agents/neutron-agent-l3
@@ -205,10 +205,14 @@ neutron_l3_agent_status() {
     fi
 }
 
+# modified by mpatterson@bluebox.net
+#
+# neutron_l3_agent_monitor queries neutron agent cmds 
+# rather than relying on netstat for service status
 neutron_l3_agent_monitor() {
     local rc
     local pid
-    local network_amqp_check
+    local os_rc_file=/root/stackrc
     
     neutron_l3_agent_status
     rc=$?
@@ -218,19 +222,18 @@ neutron_l3_agent_monitor() {
         return $rc
     fi
 
-    # Check the connections according to the PID.
-    # We are sure to hit the scheduler process and not other Neutron process with the same connection behavior (for example neutron-server)
-       # pid=`cat $OCF_RESKEY_pid`
-        # check the connections according to the PID
-      #  network_amqp_check=`netstat -punt | grep -s "$OCF_RESKEY_neutron_server_port" | grep -s "$pid" | grep -qs "ESTABLISHED"`
-      #  rc=$?
-      #	    if [ $rc -ne 0 ]; then
-	#        ocf_log err "Neutron L3 Server is not connected to the Neutron server: $rc"
-	#        return $OCF_NOT_RUNNING
-	#    fi
-
-	. /root/stackrc 
-	rc=$(/usr/local/bin/neutron agent-show `/usr/local/bin/neutron agent-list | grep -i l3 | awk '{print \$2}'` | grep -i alive | grep -i true > /dev/null 2>&1 && echo "pass" || echo "fail")
+    # Query neutron agent commands to verify that the agent service is actually alive
+    # rather than just looking for a valid pid.
+    #
+    # source openstack rc file
+    if [ -f $os_rc_file ]; then 
+      . $os_rc_file
+    else
+      echo "No Openstack Source File Exists at: $os_rc_file"
+	    return $OCF_NOT_RUNNING
+    fi
+ 
+    rc=$(/usr/local/bin/neutron agent-show `/usr/local/bin/neutron agent-list | grep -i l3 | grep $(/bin/hostname) | awk '{print \$2}'` | grep -i alive | grep -i true > /dev/null 2>&1 && echo "pass" || echo "fail")
 
 	if [ $rc != "pass" ]; then
 	    ocf_log err "Neutron L3 Server is not connected to the Neutron server: $rc" 
@@ -241,6 +244,11 @@ neutron_l3_agent_monitor() {
 	fi 
 }
 
+# modified by mpatterson@bluebox.net
+#
+# neutron_l3_agent_start now _only_ supports
+# an upstart managed neutron-l3-agent daemon.
+# (as opposed to only supporting the agent binary directly)
 neutron_l3_agent_start() {
     local rc
 
@@ -251,14 +259,8 @@ neutron_l3_agent_start() {
         return $OCF_SUCCESS
     fi
 
-    #
-    # --config-dir added and --log-file changed by mpatterson@bluebox.net
-    #
-    # run the actual neutron-l3-agent daemon. Don't use ocf_run as we're sending the tool's output
-    # straight to /dev/null anyway and using ocf_run would break stdout-redirection here.
-    su ${OCF_RESKEY_user} -s /bin/sh -c "${OCF_RESKEY_binary} --config-dir /etc/neutron --config-file=$OCF_RESKEY_config \
-      --config-file=$OCF_RESKEY_plugin_config --log-file=/var/log/upstart/neutron-l3-agent.log $OCF_RESKEY_additional_parameters"' >> \
-	/dev/null 2>&1 & echo $!' > $OCF_RESKEY_pid
+    /sbin/start neutron-l3-agent
+    rc=$?
 
     # Spin waiting for the server to come up.
     # Let the CRM/LRM time us out if required
@@ -277,6 +279,15 @@ neutron_l3_agent_start() {
     return $OCF_SUCCESS
 }
 
+
+# modified by mpatterson@bluebox.net
+#
+# neutron_l3_agent_stop now _only_ supports
+# an upstart managed neutron-l3-agent daemon.
+# (as opposed to only supporting the agent binary directly)
+#
+# This is necessary, otherwise upstart's respawn
+# prevents l3 agent process from being killed 
 neutron_l3_agent_stop() {
     local rc
     local pid
@@ -288,45 +299,17 @@ neutron_l3_agent_stop() {
         return $OCF_SUCCESS
     fi
 
-    # Try SIGTERM
-    pid=`cat $OCF_RESKEY_pid`
-    ocf_run kill -s TERM $pid
+    # Try stop via upstart
+    /sbin/stop neutron-l3-agent
     rc=$?
+
     if [ $rc -ne 0 ]; then
         ocf_log err "OpenStack L3 Server (neutron-l3-agent) couldn't be stopped"
         exit $OCF_ERR_GENERIC
     fi
 
-    # stop waiting
-    shutdown_timeout=15
-    if [ -n "$OCF_RESKEY_CRM_meta_timeout" ]; then
-        shutdown_timeout=$((($OCF_RESKEY_CRM_meta_timeout/1000)-5))
-    fi
-    count=0
-    while [ $count -lt $shutdown_timeout ]; do
-        neutron_l3_agent_status
-        rc=$?
-        if [ $rc -eq $OCF_NOT_RUNNING ]; then
-            break
-        fi
-        count=`expr $count + 1`
-        sleep 1
-        ocf_log debug "OpenStack L3 Server (neutron-l3-agent) still hasn't stopped yet. Waiting ..."
-    done
-
-    neutron_l3_agent_status
-    rc=$?
-    if [ $rc -ne $OCF_NOT_RUNNING ]; then
-        # SIGTERM didn't help either, try SIGKILL
-        ocf_log info "OpenStack L3 Server (neutron-l3-agent) failed to stop after ${shutdown_timeout}s \
-          using SIGTERM. Trying SIGKILL ..."
-        ocf_run kill -s KILL $pid
-    fi
-
+    test -e $OCF_RESKEY_pid && rm $OCF_RESKEY_pid
     ocf_log info "OpenStack L3 Server (neutron-l3-agent) stopped"
-
-    rm -f $OCF_RESKEY_pid
-
     return $OCF_SUCCESS
 }
 
